version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: BlueGreenTask:2
        LoadBalancerInfo:
          ContainerName: bluegreen
          ContainerPort: 80